sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Jrf4c7iUzlKviGo4LhQE0nOYwW6KSI96IfxsJ0s0xaJ6Fv+w9dZco7x+kSdchHx1c2vErzONEE5VS5UMGz5BG/2jSB1LoJHNF62OljU1QkeGrwTkzCelj30Zxb5LPW6bbgqcc56xXCuTqPEMXEqF4dr8K+utzHp4vRAv2cRZCBRYfB8qa+vL1bdcQ5V+oPVKFC9Sgy5yDSmAbgKfwQ9jxEn4tyH4pTl4p0oO8kV1yej96Q50q7XBDVFRl1oSGwdcyqTpbwRSTmrlXQVdj1cp1H1S9XvsexzKrZvGhYU/wWyZHkcWS6i6DPs3MQ4nFOQxYL+6GCSSkwN1Y1VvUznn2WQBfi1Jd+zmBqYVtX/gBdlMKNCki1isY9Ps4b2W0xRROXhEstKYUzimrUu8Os+XBIrWjODquP0H8Re9EEBzUJR18RLQ1I+h+fyNtyyp5wHju2FpnrxMri7jWLgD1TlaXOXjwjVZ/Y1wShtIjB/ISLlYwjfDJKtutz/XNbABeQGXUa8R/mh+R0l1XT7Bq78W3nfk9Ji5C+KF7qOt+D4PrEKhaYYB004H1VZ6wApo37Zj5P6Vsuzu5PJkeO1yWqX05Mdr5aZZ3fEQZZitehSwg1zFfoKqcoCFNxQcnECbTZQaoyXHDO80HontdWAcdin3LoK3gEcRwTq91JZi+SEdfa4=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Complete-Poetical-Works-of-Percy-Bysshe-Shelley-Complete_4800
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy